# Reading csv and excel files

In [1]:
# importing pandas library
import pandas as pd

In [2]:
# Reading csv file
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/2. Python for ML/data.csv')

In [4]:
df.head() # first five rows

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [5]:
# Read excel file
df1 = pd.read_excel('/content/drive/MyDrive/Machine Learning/2. Python for ML/data.xlsx')

In [6]:
df1.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

# Dataframe and Basic operations

In [7]:
import pandas as pd

In [10]:
# Reading csv file
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/2. Python for ML/data2.csv')

In [11]:
# Dimension
df.shape

(699, 11)

In [12]:
# first 5 rows
df.head()

        ID  Clump_Thickness  ...  Mitoses  Cancer_Type
0  1000025                5  ...        1            2
1  1002945                5  ...        1            2
2  1015425                3  ...        1            2
3  1016277                6  ...        1            2
4  1017023                4  ...        1            2

[5 rows x 11 columns]

In [13]:
# bottom 5 rows
df.tail()

         ID  Clump_Thickness  ...  Mitoses  Cancer_Type
694  776715                3  ...        1            2
695  841769                2  ...        1            2
696  888820                5  ...        2            4
697  897471                4  ...        1            4
698  897471                4  ...        1            4

[5 rows x 11 columns]

In [14]:
# all column names
df.columns

Index(['ID', 'Clump_Thickness', 'Cell_Size_Uniformity',
       'Cell_Shape_Uniformity', 'Marginal_Adhesion',
       'Single_Epithelial_Cell_Size', 'Bare_Nuclei', 'Bland_Chromatin',
       'Normal_Nucleoli', 'Mitoses', 'Cancer_Type'],
      dtype='object')

In [15]:
# single column
df['Bare_Nuclei']

0       1
1      10
2       2
3       4
4       1
       ..
694     2
695     1
696     3
697     4
698     5
Name: Bare_Nuclei, Length: 699, dtype: object

In [17]:
# multiple column
df[['Bare_Nuclei','Cancer_Type']]

    Bare_Nuclei  Cancer_Type
0             1            2
1            10            2
2             2            2
3             4            2
4             1            2
..          ...          ...
694           2            2
695           1            2
696           3            4
697           4            4
698           5            4

[699 rows x 2 columns]

# Indexing in DataFrame

In [18]:
df.iloc[:5] # first 5 rows

        ID  Clump_Thickness  ...  Mitoses  Cancer_Type
0  1000025                5  ...        1            2
1  1002945                5  ...        1            2
2  1015425                3  ...        1            2
3  1016277                6  ...        1            2
4  1017023                4  ...        1            2

[5 rows x 11 columns]

In [19]:
df.iloc[:,:2] # first 2 column

          ID  Clump_Thickness
0    1000025                5
1    1002945                5
2    1015425                3
3    1016277                6
4    1017023                4
..       ...              ...
694   776715                3
695   841769                2
696   888820                5
697   897471                4
698   897471                4

[699 rows x 2 columns]

In [21]:
df[df['Cancer_Type'] == 2] # Condition

          ID  Clump_Thickness  ...  Mitoses  Cancer_Type
0    1000025                5  ...        1            2
1    1002945                5  ...        1            2
2    1015425                3  ...        1            2
3    1016277                6  ...        1            2
4    1017023                4  ...        1            2
..       ...              ...  ...      ...          ...
690   654546                1  ...        1            2
692   714039                3  ...        1            2
693   763235                3  ...        2            2
694   776715                3  ...        1            2
695   841769                2  ...        1            2

[458 rows x 11 columns]